### ISSUE TITLE
/usr/bin/nfd: Operation not permitted

### ISSUE THREAD

**Issue by justincpresley** [yoursunny/NFD-nightly#1]
**Environment:**

We are using this Dockerfile image: https://github.com/cbmckni/ndn-tools-docker.
This pulls the latest nighty package for Ubuntu 18.04.
It also creates some aliases and sets up some basic things needed for kubernetes.

**Problem:**

![Capture](https://user-images.githubusercontent.com/31783047/127403239-1b72e0c7-e20d-436e-bcfd-1427246babe9.PNG)

For both the root user and running it with sudo, nfd seemed to not allow me to run it.

**Comment by yoursunny** [comment]
My packages are built from the [named-data/ppa-packaging](https://github.com/named-data/ppa-packaging).
You'll see the exact same error if you install from [named-data/ppa](https://launchpad.net/~named-data/+archive/ubuntu/ppa).
This is not a bug in my build procedure, as I do not modify build scripts other than overwriting version numbers.

**/usr/bin/nfd: Operation not permitted** error is caused by `nfd` binary asking for NET\_ADMIN capability but Docker container by default does not grant this capability.
This capability was granted in [nfd.postinst](https://github.com/named-data/ppa-packaging/blob/995b4d945490b2b10adfedb62ba558f02d4bec8d/nfd/debian/nfd.postinst#L27).
Having a capabilities granted by `setcap` but unavailable in the container is what caused the program to fail to start.

NFD runs as root in Docker containers, so that it's unnecessary to set any capabilities on the file.
It's recommended that Dockerfile should remove capabilities after installation.
See [this example](https://github.com/usnistgov/ndn-dpdk/blob/5cc408c03c35a9dffda9330b89d021e87e137985/docs/interop/nfd/Dockerfile#L10).
A similar Dockerfile is used on [ndn6 network](https://yoursunny.com/p/ndn6/) and it works fine for UDP/IPv6 connections.

Ethernet faces will require NET\_ADMIN capability when you launch the container.
See [Ethernet unicast](https://github.com/usnistgov/ndn-dpdk/blob/5cc408c03c35a9dffda9330b89d021e87e137985/docs/interop/NFD.md#ethernet-unicast-over-a-link) on how to grant this capability on the command line and then pass the network interface to the container.
Even in this case, it's unnecessary to have capabilities on the file, because NFD runs as root.
