### ISSUE TITLE
Running ndn-cxx trivial examples with NFD-nightly

### ISSUE THREAD

**Issue by justincpresley** [yoursunny/NFD-nightly#5]
I may be blind to using C++ packages in general but I aim to learn. I figured that reaching out was the best way to get the answers I require the quickest. Hopefully you have time to help me.

I am using NFD-nightly, I have it fully installed with ndn-cxx, and I am looking to how I would compile C++ with the installed library.
Lets say, I want to compile the [simple consumer and producer](https://www.named-data.net/doc/ndn-cxx/current/examples.html) which leads me to have consumer.cpp and producer.cpp. How would I then compile them using g++ (without forming an entire waf build config)?

Modifying the statement below..
g++ -o producer producer.cpp // throws errors relating to the library

**Comment by yoursunny** [comment]
To compile a single-file ndn-cxx program, you need these packages:

* build-essential
* libndn-cxx-dev

Then you can run:

```bash
g++ -o program program.cpp $(pkg-config --cflags --libs libndn-cxx)
```

It isn't possible to download source code with `apt source` command because source code isn't published on NFD-nightly APT repository.
You can find the commit hash in package version and then download source code from upstream repositories.

**Comment by yoursunny** [comment]
A [failed build in NFD-nightly](https://github.com/yoursunny/NFD-nightly/runs/5525230802) prompts me to amend the above suggestion.
The command should be:

```bash
g++ -std=c++17 -o program program.cpp $(pkg-config --cflags --libs libndn-cxx)
```

ndn-cxx code is best compiled in C++17 mode, but the pkg-config does not emit the `-std=` flag.
Therefore, it needs to be specified on the command line.
